version: 0.1

workflows:
  main:
    jobs:
    - build

jobs:
  build:
    steps:
    - clone
    - run: wodby ci init $WODBY_BUILD_ID
    - run: wodby ci run -- go test ./...
    - run: wodby ci run -- go vet ./...
    - run: wodby ci build go -f Dockerfile
    - run: wodby ci push
    - run: wodby ci deploy
